# Generated by Django 4.2 on 2025-07-15 01:42

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autores',
            fields=[
                ('id_autor', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('data_falecimento', models.DateField(blank=True, null=True)),
                ('local_nascimento', models.CharField(blank=True, max_length=100, null=True)),
                ('biografia', models.TextField(blank=True, null=True)),
                ('foto', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='autores/')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Editoras',
            fields=[
                ('id_editora', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('localizacao', models.CharField(blank=True, max_length=255, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fotografos',
            fields=[
                ('id_fotografo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Revistas',
            fields=[
                ('id_revista', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('edicao', models.CharField(max_length=100)),
                ('ano_publicacao', models.IntegerField()),
                ('capa_url', models.URLField(blank=True, max_length=255, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('editora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revistas', to='core.editoras')),
            ],
        ),
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id_livro', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=100)),
                ('ano_publicacao', models.IntegerField()),
                ('sinopse', models.TextField(blank=True, null=True)),
                ('capa', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='livros/capas/')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livros', to='core.autores')),
            ],
        ),
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id_foto', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=500)),
                ('local', models.CharField(max_length=200)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('fotografo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='core.fotografos')),
            ],
        ),
    ]
