# Generated by Django 4.2 on 2025-06-14 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        # Comentar/Remover se 'core_editoras' JÁ EXISTE no BD
        # migrations.CreateModel(
        #     name='Editoras',
        #     fields=[
        #         ('id_editora', models.AutoField(primary_key=True, serialize=False)),
        #         ('nome', models.CharField(max_length=100)),
        #         ('localizacao', models.CharField(blank=True, max_length=255, null=True)),
        #         ('data_cadastro', models.DateTimeField(auto_now_add=True)),
        #     ],
        # ),
        # Manter se 'core_fotografos' NÃO EXISTE e precisa ser criada.
        # Caso contrário, comente/remova.
        migrations.CreateModel(
            name='Fotografos',
            fields=[
                ('id_fotografo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        # ESTA PARTE É ESSENCIAL E DEVE PERMANECER
        migrations.AddField(
            model_name='autores',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        # Comentar/Remover se 'core_revistas' JÁ EXISTE no BD
        # migrations.CreateModel(
        #     name='Revistas',
        #     fields=[
        #         ('id_revista', models.AutoField(primary_key=True, serialize=False)),
        #         ('titulo', models.CharField(max_length=200)),
        #         ('edicao', models.CharField(max_length=100)),
        #         ('ano_publicacao', models.IntegerField()),
        #         ('capa_url', models.URLField(blank=True, max_length=255, null=True)),
        #         ('data_cadastro', models.DateTimeField(auto_now_add=True)),
        #         ('editora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revistas', to='core.editoras')),
        #     ],
        # ),
        # Comentar/Remover se 'core_livros' JÁ EXISTE no BD
        # migrations.CreateModel(
        #     name='Livros',
        #     fields=[
        #         ('id_livro', models.AutoField(primary_key=True, serialize=False)),
        #         ('titulo', models.CharField(max_length=200)),
        #         ('genero', models.CharField(max_length=100)),
        #         ('ano_publicacao', models.IntegerField()),
        #         ('sinopse', models.TextField(blank=True, null=True)),
        #         ('capa_url', models.URLField(blank=True, max_length=255, null=True)),
        #         ('data_cadastro', models.DateTimeField(auto_now_add=True)),
        #         ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livros', to='core.autores')),
        #     ],
        # ),
        # Manter se 'core_fotos' NÃO EXISTE e precisa ser criada.
        # Caso contrário, comente/remova.
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id_foto', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=500)),
                ('local', models.CharField(max_length=200)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('fotografo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='core.fotografos')),
            ],
        ),
    ]