# Generated by Django 4.2 on 2025-05-22 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_livros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editoras',
            fields=[
                ('id_editora', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('localizacao', models.CharField(blank=True, max_length=255, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Revistas',
            fields=[
                ('id_revista', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('edicao', models.CharField(max_length=100)),
                ('ano_publicacao', models.IntegerField()),
                ('capa_url', models.URLField(blank=True, max_length=255, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('editora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revistas', to='core.editoras')),
            ],
        ),
    ]
