# Generated by Django 4.2 on 2025-07-18 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_livros_capa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livros',
            old_name='capa',
            new_name='capa_url',
        ),
    ]
