# Generated by Django 4.2 on 2025-07-18 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_capa_livros_capa_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livros',
            old_name='capa_url',
            new_name='capa',
        ),
    ]
