# Generated by Django 4.2 on 2025-08-12 16:46

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_capa_url_livros_capa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autores',
            options={'ordering': ['nome', 'sobrenome'], 'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterModelOptions(
            name='editoras',
            options={'ordering': ['nome'], 'verbose_name': 'Editora', 'verbose_name_plural': 'Editoras'},
        ),
        migrations.AlterModelOptions(
            name='fotografos',
            options={'ordering': ['nome'], 'verbose_name': 'Fotógrafo', 'verbose_name_plural': 'Fotógrafos'},
        ),
        migrations.AlterModelOptions(
            name='fotos',
            options={'ordering': ['-ano', 'titulo'], 'verbose_name': 'Foto', 'verbose_name_plural': 'Fotos'},
        ),
        migrations.AlterModelOptions(
            name='livros',
            options={'ordering': ['-ano_publicacao', 'titulo'], 'verbose_name': 'Livro', 'verbose_name_plural': 'Livros'},
        ),
        migrations.AlterModelOptions(
            name='revistas',
            options={'ordering': ['-ano_publicacao', 'titulo'], 'verbose_name': 'Revista', 'verbose_name_plural': 'Revistas'},
        ),
        migrations.RemoveField(
            model_name='revistas',
            name='capa_url',
        ),
        migrations.AddField(
            model_name='editoras',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='fotografos',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='fotos',
            name='ano',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fotos',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fotos',
            name='imagem',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='fotos/'),
        ),
        migrations.AddField(
            model_name='fotos',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='livros',
            name='editora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livros', to='core.editoras'),
        ),
        migrations.AddField(
            model_name='revistas',
            name='capa',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='revistas/'),
        ),
        migrations.AddField(
            model_name='revistas',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='livros',
            name='genero',
            field=models.CharField(choices=[('CONTO', 'Contos'), ('ROMANCE', 'Romance'), ('POESIA', 'Poesia'), ('CRONICA', 'Crônica'), ('ENSAIO', 'Ensaio'), ('OUTRO', 'Outro')], max_length=100),
        ),
    ]
