# Generated by Django 4.2 on 2025-08-13 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_autores_options_alter_editoras_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenciaPesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Referência de Pesquisa',
                'verbose_name_plural': 'Referências de Pesquisa',
            },
        ),
        migrations.CreateModel(
            name='TrechoLivro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(help_text='Trecho selecionado do livro')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem do trecho no livro (opcional)')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trechos', to='core.livros')),
            ],
            options={
                'verbose_name': 'Trecho do Livro',
                'verbose_name_plural': 'Trechos dos Livros',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.AddField(
            model_name='autores',
            name='referencias',
            field=models.ManyToManyField(blank=True, related_name='autores', to='core.referenciapesquisa'),
        ),
    ]
