# Generated by Django 4.2 on 2025-08-13 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_referenciapesquisa_trecholivro_autores_referencias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título da referência ou site', max_length=255)),
                ('descricao', models.TextField(blank=True, help_text='Descrição opcional', null=True)),
                ('tem_link', models.BooleanField(default=False, help_text='Marque se existe um link para a referência')),
                ('link', models.URLField(blank=True, help_text='URL da referência (opcional)', null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Referência de Pesquisa',
                'verbose_name_plural': 'Referências de Pesquisa',
                'ordering': ['-data_cadastro', 'titulo'],
            },
        ),
        migrations.RemoveField(
            model_name='autores',
            name='referencias',
        ),
        migrations.DeleteModel(
            name='ReferenciaPesquisa',
        ),
        migrations.AddField(
            model_name='referencias',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencias', to='core.autores'),
        ),
    ]
