# Generated by Django 4.2 on 2025-08-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_referencias_remove_autores_referencias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencias',
            name='data_acesso',
            field=models.DateField(blank=True, help_text='Data de acesso ao site (para ABNT)', null=True),
        ),
    ]
