# Generated by Django 4.2 on 2025-08-13 19:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_referencias_data_acesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='revistas',
            name='pdf',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='revistas/pdfs/'),
        ),
    ]
