# Generated by Django 4.2 on 2025-09-04 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_revistas_pdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referencias',
            old_name='autor',
            new_name='autor_biografado',
        ),
        migrations.AddField(
            model_name='referencias',
            name='autor_referencia',
            field=models.CharField(blank=True, help_text='Nome do autor da referência', max_length=200, null=True),
        ),
    ]
