# Generated by Django 4.2 on 2025-09-04 23:31

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_noticias'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='autor_nome',
            field=models.CharField(blank=True, help_text='Nome do autor se não for um autor cadastrado', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='noticias',
            name='destaque',
            field=models.BooleanField(default=False, help_text='Define se a notícia aparece em destaque'),
        ),
        migrations.AddField(
            model_name='noticias',
            name='imagem_capa_legenda',
            field=models.CharField(blank=True, help_text='Legenda da imagem de capa', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='noticias',
            name='publicada',
            field=models.BooleanField(default=True, help_text='Define se a notícia está publicada'),
        ),
        migrations.AddField(
            model_name='noticias',
            name='subtitulo',
            field=models.CharField(blank=True, help_text='Subtítulo ou descrição breve da notícia', max_length=300, null=True),
        ),
        migrations.CreateModel(
            name='ImagemNoticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='noticias/extras/')),
                ('legenda', models.CharField(blank=True, max_length=200, null=True)),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição da imagem na notícia')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens_extras', to='core.noticias')),
            ],
            options={
                'verbose_name': 'Imagem da Notícia',
                'verbose_name_plural': 'Imagens das Notícias',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
