# Generated by Django 4.2 on 2025-09-15 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_noticias_autor_nome_noticias_destaque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='data_edicao',
            field=models.DateTimeField(auto_now=True, help_text='Data da última edição'),
        ),
        migrations.AddField(
            model_name='noticias',
            name='resumo',
            field=models.TextField(blank=True, help_text='Resumo da notícia para SEO e compartilhamento', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='noticias',
            name='tags',
            field=models.CharField(blank=True, help_text='Tags separadas por vírgula (ex: modernismo, literatura, minas gerais)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='noticias',
            name='tempo_leitura',
            field=models.PositiveIntegerField(blank=True, help_text='Tempo estimado de leitura em minutos', null=True),
        ),
        migrations.AddField(
            model_name='noticias',
            name='visualizacoes',
            field=models.PositiveIntegerField(default=0, help_text='Número de visualizações da notícia'),
        ),
        migrations.CreateModel(
            name='ReferenciaNoticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título da referência', max_length=255)),
                ('autor_referencia', models.CharField(blank=True, help_text='Nome do autor da referência', max_length=200, null=True)),
                ('descricao', models.TextField(blank=True, help_text='Descrição ou resumo da referência', null=True)),
                ('link', models.URLField(blank=True, help_text='URL da referência', null=True)),
                ('data_acesso', models.DateField(blank=True, help_text='Data de acesso (para referências online)', null=True)),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencias', to='core.noticias')),
            ],
            options={
                'verbose_name': 'Referência da Notícia',
                'verbose_name_plural': 'Referências das Notícias',
                'ordering': ['ordem', 'titulo'],
            },
        ),
    ]
