# Generated by Django 4.2 on 2025-09-16 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_noticias_data_edicao_noticias_resumo_noticias_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotos',
            name='fotografo',
            field=models.ForeignKey(blank=True, help_text='Fotógrafo responsável pela foto (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotos', to='core.fotografos'),
        ),
    ]
