# Generated by Django 4.2 on 2025-09-16 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_fotos_fotografo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotos',
            name='fotografo',
        ),
    ]
